### ISSUE TITLE
ftp doesn't handle timed out error

### ISSUE THREAD

**Issue by cliffano** [cliffano/sendman#2]
Found this while testing 2000 images upload to GoDaddy server.
When the server timed out, ftp-deploy throws an error and there's currently no handling.
One possible solution is to retry with max_retries and delay options.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ETIMEDOUT
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)

**Comment by cliffano** [comment]
Done. Included in release v0.2.1 ."
